/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.*;
import controller.*;
/**
 *
 * @author pc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Gerenciamento
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        barraMenuFormGerenciamento = new javax.swing.JMenuBar();
        menuGerenciamento = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenu();
        itemGrupos = new javax.swing.JMenuItem();
        menuGrupoPesquisa = new javax.swing.JMenu();
        menuIniciarGrupoPesquisa = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuVerRelatorios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        labelLogin.setText("LOGIN");

        labelSenha.setText("SENHA");

        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        menuGerenciamento.setText("Gerenciamento");

        menuCadastro.setText("Cadastrar");

        itemGrupos.setText("Grupos ");
        itemGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemGruposMouseClicked(evt);
            }
        });
        itemGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGruposActionPerformed(evt);
            }
        });
        menuCadastro.add(itemGrupos);

        menuGerenciamento.add(menuCadastro);

        barraMenuFormGerenciamento.add(menuGerenciamento);

        menuGrupoPesquisa.setText("Grupo de Pesquisa");

        menuIniciarGrupoPesquisa.setText("Iniciar");
        menuGrupoPesquisa.add(menuIniciarGrupoPesquisa);

        barraMenuFormGerenciamento.add(menuGrupoPesquisa);

        menuRelatorios.setText("Relatórios");

        menuVerRelatorios.setText("Ver");
        menuRelatorios.add(menuVerRelatorios);

        barraMenuFormGerenciamento.add(menuRelatorios);

        setJMenuBar(barraMenuFormGerenciamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEntrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(txtLogin)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelLogin)
                                .addComponent(labelSenha))))
                    .addContainerGap(148, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(labelLogin)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(labelSenha)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnEntrar)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // IF PARA VERIFICAÇÃO SE O LOGIN E SENHA ESTÃO CORRETOS DE ACORDO COM O BANCO DE DADOS 
        String login = txtLogin.getText();
        String senha = txtSenha.getText();
        String $login = "a";
        String $senha = "1";
        
        if(login.equals($login) && senha.equals($senha)){
           
            menuGerenciamento.setEnabled(true);
            menuGrupoPesquisa.setEnabled(true);
            menuRelatorios.setEnabled(true);
            
            labelLogin.setText("Bem vindo!");
            labelSenha.setVisible(false);
            txtSenha.setVisible(false);
            txtLogin.setVisible(false);
            btnEntrar.setVisible(false);
            
             //JOptionPane.showMessageDialog(rootPane, "Usuário logado!");
           
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        menuGerenciamento.setEnabled(false);
        menuGrupoPesquisa.setEnabled(false);
        menuRelatorios.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void itemGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGruposActionPerformed
        // TODO add your handling code here:
        
       Cadastro formCadastro = new Cadastro();
       
       formCadastro.setVisible(true);
       
       
    }//GEN-LAST:event_itemGruposActionPerformed

    private void itemGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemGruposMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itemGruposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //teste para conexão do hibernate
//        
//        Pessoa pessoaTeste = new Pessoa(0,"Pessoa teste Aluno");
//        PessoaController controllerPTeste = new PessoaController();
//        controllerPTeste.salvar(pessoaTeste);
//        //pessoaTeste = controllerPTeste.get(1);
//        
//        Pessoa pessoaTeste2 = new Pessoa(0,"Pessoa teste Tecnico");
//        PessoaController controllerPTeste2 = new PessoaController();
//        controllerPTeste2.salvar(pessoaTeste2);
//        
//        Pessoa pessoaTeste3 = new Pessoa(0,"Pessoa teste Orientador");
//        PessoaController controllerPTeste3 = new PessoaController();
//        controllerPTeste3.salvar(pessoaTeste3);
//        
//        Aluno alunoTeste = new Aluno(0, pessoaTeste);
//        AlunoController controllerATeste = new AlunoController();
//        controllerATeste.salvar(alunoTeste);
//        
//        Tecnico tecnicoTeste = new Tecnico(0, pessoaTeste2);
//        TecnicoController controllerTTeste = new TecnicoController();
//        controllerTTeste.salvar(tecnicoTeste);
//        
//        Orientador OrientadorTeste = new Orientador(0, pessoaTeste3);
//        OrientadorController controllerOTeste = new OrientadorController();
//        controllerOTeste.salvar(OrientadorTeste);
        
        //TesteJFrame teste1 = new TesteJFrame();
        //Teste1.show();
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuFormGerenciamento;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JMenuItem itemGrupos;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuGerenciamento;
    private javax.swing.JMenu menuGrupoPesquisa;
    private javax.swing.JMenuItem menuIniciarGrupoPesquisa;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuVerRelatorios;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
